### ISSUE TITLE
Windows安装完运行会出现ddl缺失

### ISSUE THREAD

**Issue by FFFcat** [jwenjian/lucky-you#1]
直接安装完点击运行的话会出现ddl报错，需要下载这个[文件](https://cn.dll-files.com/vcruntime140_1.dll.html)拷贝到`C:\Windows\System32\` 才可以运行，希望能集成。
还有一些小建议，
1. 建议给音效加个开关。
2. 图片下方的文字建议选用文件名的显示，我这里显示的是绝对路径，太长了看不到文件名。

感谢作者。

**Comment by jwenjian** [comment]
好的，关于这个 dll 的问题，由于我手头没有 windows 本，所以没法测试，感谢你的反馈，我会去 tauri 反馈一下，看是不是他们的框架没有处理好这个 dll。

另外，音效开关也在后续的迭代计划中。

关于绝对路径的问题，我这里再看一下，可能 mac 和 windows 上的表现有差异。

**Comment by jwenjian** [comment]
这个issue好像是可以解决，不过我还没有试，https://github.com/tauri-apps/tauri/issues/719

**Comment by jwenjian** [comment]
@FFFcat 新版本 release 了，https://github.com/jwenjian/lucky-you/releases/tag/v0.3.0， 麻烦验证以下音效开关和文件名的问题，多谢。

**Comment by jwenjian** [comment]
@FFFcat hello, 看看有没有时间帮忙测试一下新版本，这个版本应该是解决了那个 dll 的问题，可能需要你先手动把那个 dll 从 `C:/Windows/System32` 中删掉，然后安装一下，看看还报不报那个错误，非常感谢

**Comment by FFFcat** [comment]
抱歉，最近考试没空看。。dll的问题还存在，路径是相对路径了，声音按钮也测试成功了。

**Comment by jwenjian** [comment]
@FFFcat 好的，感谢反馈，dll 的问题我之后会再关注，现在已经在 README 上提醒了

PS. Windows上真的很多问题，打出来的 Mac 包都没问题。。。
