### ISSUE TITLE
build bug ?

### ISSUE THREAD

**Issue by reclusegit** [jwenjian/lucky-you#10]
**Describe the bug / 描述你遇到的问题**

build的时候报错，请求帮助，错误如下：

[tauri]: running build
 app:tauri (runner) Error: cannot find index.html in "/Users/reclusemac/dev/githubrap/lucky-you/dist_tauri/bundled". Did you forget to build your web code or update the build.distDir in tauri.conf.json? +0ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**To Reproduce / 重现步骤**

1. yarn tauri build --release
2. 
3. 
4. 

❯ yarn tauri info
yarn run v1.22.10
$ /Users/reclusemac/dev/githubrap/lucky-you/node_modules/.bin/tauri info
[tauri]: running info

Operating System - Darwin(20.2.0) - darwin/x64

Node.js environment
  Node.js - 15.4.0
  tauri.js - 0.14.1

Rust environment
  rustc - 1.50.0-nightly
  cargo - 1.50.0-nightly
  tauri-bundler - 0.9.4

Global packages
  NPM - 7.0.15
  yarn - 1.22.10

App directory structure
/.git
/.github
/.history
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.7.5 (outdated, latest: 0.11.1)
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist_tauri/bundled
  devPath - http://localhost:3000
✨  Done in 4.12s.

**Comment by jwenjian** [comment]
Since the tauri updated many versions, I will take some time to update to latest version, after that, you can try to build again.

Will let you know once I finished. :)

**Comment by reclusegit** [comment]
> Since the tauri updated many versions, I will take some time to update to latest version, after that, you can try to build again.
> 
> Will let you know once I finished. :)

Thanks
