### ISSUE TITLE
Showcase Removal Notice

### ISSUE THREAD

**Issue by JonasKruckenberg** [jwenjian/lucky-you#13]
Hello friends of Tauri,
With the upcoming v1 release and accompanying overhaul of the https://tauri.studio website, we will be removing the showcase section in favor of [**Awesome Tauri**](https://github.com/tauri-apps/awesome-tauri). 
If you want to keep your project featured, please submit it to that list instead, but please note the rules for submissions have changed.

Thank you for all your support in getting Tauri to this point!

Jonas,
the Tauri team

**Comment by jwenjian** [comment]
Noted



发自我的iPhone


------------------ Original ------------------
From: Jonas Kruckenberg ***@***.***&gt;
Date: Tue,Feb 8,2022 7:04 PM
To: jwenjian/lucky-you ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [jwenjian/lucky-you] Showcase Removal Notice (Issue #13)





 
Hello friends of Tauri,
 With the upcoming v1 release and accompanying overhaul of the https://tauri.studio website, we will be removing the showcase section in favor of Awesome Tauri.
 If you want to keep your project featured, please submit it to that list instead, but please note the rules for submissions have changed.
 
Thank you for all your support in getting Tauri to this point!
 
Jonas,
 the Tauri team
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
